apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-contactpoints
  namespace: monitoring
  labels:
    grafana_alert: "1"
data:
  contactpoints.yaml: |
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: email-gmail
        receivers:
          - uid: email-gmail
            type: email
            settings:
              addresses: "segg3r@gmail.com"
    notificationPolicies:
      - orgId: 1
        receiver: email-gmail
        group_by: [alertname]
        group_wait: 10s
        group_interval: 1m
        repeat_interval: 4h
        routes: []


