apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: activemq-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: activemq
  endpoints:
    - port: metrics
      interval: 15s


